# Generated by Django 3.2.8 on 2022-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, verbose_name='カテゴリー名映画'),
        ),
    ]
